# Generated by Django 3.0 on 2024-12-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0029_auto_20241127_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
