# Generated by Django 3.0 on 2024-12-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0030_stock_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferreditem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.DeleteModel(
            name='TransferredItem',
        ),
    ]
