# Generated by Django 3.0 on 2024-12-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0031_auto_20241204_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='spareparts',
            name='sparepartsize',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
