# Generated by Django 3.0 on 2024-12-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0033_auto_20241204_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='balanceqty',
            new_name='remark',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
    ]
