# Generated by Django 3.0 on 2024-12-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0034_auto_20241205_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktodept',
            name='receivedBy',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stocktodept',
            name='sparepartsize',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
