# Generated by Django 3.0 on 2024-12-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0035_auto_20241205_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptstock',
            name='sparepartsize',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
