# Generated by Django 3.0 on 2024-12-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0036_deptstock_sparepartsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktodept',
            name='balancedqty',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stocktodept',
            name='issuedqty',
            field=models.DateField(null=True),
        ),
    ]
