# Generated by Django 3.0 on 2024-12-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0037_auto_20241205_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktodept',
            name='balancedqty',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stocktodept',
            name='issuedqty',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
