# Generated by Django 3.0 on 2024-12-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0040_auto_20241205_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='depttodept',
            name='sparepartsize',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
