# Generated by Django 3.0 on 2024-12-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0041_depttodept_sparepartsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='department',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
